// Code generated by "stringer -type=NextTurnAction ./entity"; DO NOT EDIT.

package entity

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Submit-0]
	_ = x[Voting-1]
}

const _NextTurnAction_name = "SubmitVoting"

var _NextTurnAction_index = [...]uint8{0, 6, 12}

func (i NextTurnAction) String() string {
	if i < 0 || i >= NextTurnAction(len(_NextTurnAction_index)-1) {
		return "NextTurnAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NextTurnAction_name[_NextTurnAction_index[i]:_NextTurnAction_index[i+1]]
}
